## Disk Settings ##
dir=${HOME}/Downloads
daemon=false
disk-cache=64M
file-allocation=none

## Download Settings ##
continue=true
split=16
min-split-size=1M
max-tries=5
disable-ipv6=true
max-connection-per-server=16
max-download-limit=0
max-upload-limit=0
max-overall-upload-limit=0
max-overall-download-limit=0
summary-interval=120


## More Options
allow-overwrite=true
log-level=notice
